### ISSUE TITLE
plex-auto-languages seems to be causing plex server to endlessly run operations

### ISSUE THREAD

**Issue by itsANHonor** [RemiRigal/Plex-Auto-Languages#104]
While investigating why my server was running at high CPU loads, I discovered that my Plex server was endlessly looping through some sort of operation with plex-auto-languages. The behavior would always occur at 2am when my Scheduled Plex Tasks kicked off but would continue endlessly until I stopped the docker container for plex-auto-languages. 

The logs on the plex-auto-languages docker container doesn't reveal much. I'll try and post the Plex logs as soon as I can recreate the issue again tonight. 

![plexautolanguages-dozzle](https://github.com/user-attachments/assets/5876152a-9a1d-41e9-880c-64a74dcf144a)

**Comment by itsANHonor** [comment]
These are the plex server logs

**Comment by JourneyOver** [comment]
This repository is pretty much dead in terms of development or anything really, but the only way to really fix it short of going into the code and fixing things is to disable the `scheduler` in the config file.

**Comment by itsANHonor** [comment]
Thanks, I'll give it a shot.

**Comment by itsANHonor** [comment]
@JourneyOver Unfortunately your version still is creating the same issue, but it seems to be localized to one particular show. I'll try getting Plex to ignore that one show.

**Comment by JourneyOver** [comment]
Hmm damn, sucks that it was even is doing it with my version :/ the fix for the particuler error in the image is from this PR https://github.com/RemiRigal/Plex-Auto-Languages/pull/100 which I had pushed into my version, as I was having the same issue as you for a very long time until I implemented it myself and stopped having the issues. Mind throwing up what show exactly it seems to be localized on that is possibly causing the issue still?

**Comment by JourneyOver** [comment]
Sadly I still haven't been able to reproduce the `NotImplementedError` that shows in your picture ever since forking and committing PR #100 into my fork. So I'm honestly currently stuck on trying to figure out why it's still producing the error for you.  The only other fix really is just straight up turning off the scheduler completely like suggested in #90 .

**Comment by itsANHonor** [comment]
Ah sorry to be clear, once I moved to your new image, the NotImplemented Error has gone away, but I was still getting the CPU intensive loops for that one show every night when Plex Media Server kicked off background tasks. I finally just disabled the PAL "Start on Scan" feature and it seems to have stopped that issue last night. I'm still not sure why it was so stuck on one show, but I'll keep it this way for now.

**Comment by s0len** [comment]
@JourneyOver please, can you make the tags available so I can use it in helm charts? God damn love PAL but it's unusable as is so I'd love to try your version

**Comment by JourneyOver** [comment]
@s0len to answer you both here and on #100 ;

It's already up on github located here -- https://github.com/JourneyDocker/Plex-Auto-Languages as I have it under an org that I have all my docker stuff under.

I currently don't have it setup with any tags short of just `latest` right now, but you can use either `docker.io/journeyover/plex-auto-languages:latest` or `ghcr.io/journeydocker/plex-auto-languages:latest` to use my version.

**Comment by king8084** [comment]
> This repository is pretty much dead in terms of development or anything really, but the only way to really fix it short of going into the code and fixing things is to disable the `scheduler` in the config file.
> 
> You could go and try my version if you would like and see if it works for you -- https://hub.docker.com/r/journeyover/plex-auto-languages
> 
> it has updated dependencies and I fixed up a few issues.

i cannot thank you enough, i truly thought this project was dead and as someone with anime library, this app was a god send, finally using your fork its the first time i went over an hour without crashing, infact, its been up for over 24 hours so far

i rly think you should publish this instead of forking so more people know this is still alive

**Comment by JourneyOver** [comment]
> i cannot thank you enough, i truly thought this project was dead and as someone with anime library, this app was a god send, finally using your fork its the first time i went over an hour without crashing, infact, its been up for over 24 hours so far

It's not a problem at all, glad to hear it's working for you \^^


> i rly think you should publish this instead of forking so more people know this is still alive

Not really sure what you mean by this exactly, unless you are just talking about detaching my repository from Remi's repository and turning it into a standalone repository, but tbh I don't really see a point as either way people can find it easily, and I do have it up on dockerhub, unraid, and ghcr and I've posted about my fork in several different locations.
